version: '3.1'
services:
  myjenkins:
    image: raja9658/myjenkins:1
    restart: always
    container_name: jenkins
    environment:
    - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    networks:
       mynetwork:
  mydb:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
    - MYSQL_ROOT_USERNAME=raja
    - MYSQL_ROOT_PASSWORD=12345
    - MYSQL_DATABASE=imprint_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/db
    networks:
       mynetwork:
volumes:
   jenkins-docker-certs:
   jenkins-data:
   db_data:
networks:
   mynetwork:
      driver: bridge
